### ISSUE TITLE
Is this still maintaned?

### ISSUE THREAD

**Issue by ThallesP** [calluswhatyouwant/spotify-web-sdk#116]
Hey! I see that you guys published a new version on NPM, but this repository seems not maintained.

**Comment by JoseRenan** [comment]
Hey @ThallesP, we don't actively develop new features since this version works to our needs, but we are open to new ideas and contributions 😊 

Also, if you find a bug, feel free to report!

**Comment by ThallesP** [comment]
Great, thanks!
