### ISSUE TITLE
Using pagination can break the subsequent API calls

### ISSUE THREAD

**Issue by WojciechMatuszewski** [calluswhatyouwant/spotify-web-sdk#59]
**Describe the bug**
When using pagination (cursor or page-based) `spotifyAxiosInstance.defaults.baseURL` is changed but never set back to it's original state. That causes any subsequent API calls which are not related to pagination to break (wrong url)

**To Reproduce**
1. Search for tracks using `searchTracks`
2. With recieved page call `getNextPage()`
3. Search for tracks again
4. See error (the API call fails because `baseURL` is different)
```typescript
    const instance = spotify.getAxiosSpotifyInstance();
    console.log(instance.defaults.baseURL); // https://api.spotify.com/v1
    const page = await spotify.searchTracks('lil');
    await page.getNextPage();
    console.log(instance.defaults.baseURL); // https://api.spotify.com/v1/search
    try {
        await spotify.searchTracks('peep');
    } catch (e) {
        // fails here, result call is https://api.spotify.com/v1/search/search?q=... instead of https://api.spotify.com/v1/search?q=...
        console.log('error!');
    }
```

**Expected behavior**
`spotifyAxiosInstance.defaults.baseURL` is not mutated in pagination so that user can request next page and make subsequent `searchTracks` calls without errors

**Additional context**
This is an easy fix. Instead of using `getAxiosPageInstance` inside `page.ts` or `cursor-based-page-.ts` use a method that does not modify `baseURL` like:
```typescript
    private getPagingUrl() {
        return this.href.split('?')[0];
    }
// ... //
// inside getPrevious/NextPage
 const response = await getAxiosSpotifyInstance().get(
            `${this.getPagingUrl()}/`,
            {
                params,
            }
        );
```
To prevent duplication, that method could be placed inside `uitls.ts` or `Page` and `CursorBasePage` could extend a `Pagining` class that has that method.

Thank you for this awesome package btw :)

**Comment by JoseRenan** [comment]
Thanks for reporting!!! I saw you forked the repo, are you working on the issue? Or we can assign to another person?

And thank you for using the package :heart:

**Comment by WojciechMatuszewski** [comment]
This is just a simple fix so you should expect a pr tomorrow :)
