### ISSUE TITLE
Expand type hints coverage

### ISSUE THREAD

**Issue by danielmitre** [calluswhatyouwant/spotify-web-sdk#89]
Besides having nice custom types, I found some places where the type seems to be missing. Adding type in these would enhance the experience when working in an IDE with type-hints support and help avoid bugs.

For example, this [method](https://github.com/calluswhatyouwant/spotify-web-sdk/blob/7cf2e49faa8fc81cfe1d8b1878650078ba3d7eb6/src/lib/episodes.ts#L16) seems to be missing its return type:
```ts
export const getEpisode = async (id: string, params?: { market?: string }) => {
    const response = await getAxiosSpotifyInstance().get(`/episodes/${id}`, {
        params,
    });
    return new Episode(response.data);
};
```

And I think by adding the return type, the IDE can have a nice time detecting and suggesting the valid operations with the return:
```ts
export const getEpisode = async (id: string, params?: { market?: string }): Promise<Episode> => {
    const response = await getAxiosSpotifyInstance().get(`/episodes/${id}`, {
        params,
    });
    return new Episode(response.data);
};
```

Sadly I hadn't actually used this SDK to talk about it with more property. I just explored the code because the project is awesome and suggested this hoping to contribute in its awesomeness.

**Comment by JRobsonJr** [comment]
Thanks a ton for your suggestion, @danielmitre! I'll work on this :heart:

**Comment by JRobsonJr** [comment]
I don't know why, but this wasn't closed with the PR being merged :eyes: But it's been released! Thank you once again :sparkles:
