### ISSUE TITLE
Create docs content structure

### ISSUE THREAD

**Issue by JoseRenan** [calluswhatyouwant/spotify-web-sdk#98]
**Is your feature request related to a problem? Please describe.**
Create the structure of the docs content, based on exemples such as the jest docs:
![image](https://user-images.githubusercontent.com/11728746/95633284-baf84080-0a5d-11eb-9e04-31db51d66bd3.png)

And the spotify API reference:

![image](https://user-images.githubusercontent.com/11728746/95633313-cc414d00-0a5d-11eb-821c-be9d0b990cbc.png)

**Describe the solution you'd like**

Our structure should be something like:

- Introdution (Instalation, setup and simple use, as the README already does)
- Albums (super-topic with subtopics being related functions and how to use them)
- Artists
- Browse
...
- Tracks
- User Profile
- Pagination (Section explaining the Paging Class that is used on almost all of the functions)

**Comment by Klaywert** [comment]
working on it o/
